### ISSUE TITLE
PDC we need to have check why quakes are not publishing

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#26] opened 2017-01-30 10:30 UTC
See original ticket at https://github.com/inasafe/inasafe/issues/3689 for further discussion.

**Comment by gubuntu** [comment] 2017-02-08 11:30
@lucernae have you made any inroads on this?

**Comment by lucernae** [comment] 2017-02-10 01:31
This is because celery worker is hanging.
So we need a way to reliably monitor celery worker and restart the container automatically.

**Comment by gubuntu** [comment] 2017-02-10 05:42
this should be better once you have moved it onto the new dedicated server. 

Also see if you can configure Prometheus to do celery monitoring and alerting and even automatic restarts.

**Comment by gubuntu** [comment] 2017-03-27 07:28
duplicate of #71; celery worker issue is different and is already resolved

**Closed** 2017-03-27 07:29 UTC
Labels: bug, orchestration, ready, realtime processor
