### ISSUE TITLE
Setup Docker Sync for Processed Shakemaps

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#47] opened 2017-01-31 06:39 UTC
Problem

BNPB wants to sync the processed shakemaps to their server.
Should contain the PDF and PNG files of processed shakemaps
Proposed Solution

Just setup new btsync server which shared shakemaps-extracted folders (the folder that contain all processed shakemaps with its impact layer and products).

Se original ticket at https://github.com/inasafe/inasafe/issues/3256 for further discussion.

**Comment by lucernae** [comment] 2017-02-06 17:13
duplicate of #51

**Closed by lucernae** 2017-02-06 17:13 UTC
