### ISSUE TITLE
Share InaSAFE realtime earthquake impact map with BMKG

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#45] opened 2017-01-31 06:35 UTC
BMKG has requested that InaSAFE realtime also return the impact map to them

Proposed solution
make it happen

See original ticket at https://github.com/inasafe/inasafe/issues/2986 for further discussion.

**Comment by lucernae** [comment] 2017-02-06 17:20
linked with #51

**Comment by Charlotte-Morgan** [comment] 2017-02-17 09:22
@lucernae  set up on btsync. Need to find a way to share these back to BMKG

**Comment by Charlotte-Morgan** [comment] 2017-07-13 07:24
@ivanbusthomi  - this has evolved to sharing everything - maps and data

**Comment by ivanbusthomi** [comment] 2017-08-02 06:58
> this has evolved to sharing everything - maps and data

From our last discussion, the issue is still on their preferred way of receiving the data from us.
Today I have received the contact email of Pak Artadi from BMKG who deals with technical stuff. I will write an email addresed to Pak Sigit and also cc-ing him and us in regards to this matter.

**Comment by ivanbusthomi** [comment] 2017-09-15 06:51
In the InaSAFE Traning for Situational User, I had a chance to talk with Pak Artadi about this. He said that he is already happy by accessing the result from the Earthquake Realtime website, and he thinks that it is not needed anymore to create a connection system to transfer the files.
So, I think we can close this issue. :)

**Closed** 2017-09-20 08:23 UTC
Labels: earthquake, feature request, ready, realtime processor
