### ISSUE TITLE
PetaJakarta Flood Hazard Data: migration to Petabencana.id

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#23] opened 2017-01-30 10:27 UTC
problem

PetaJakarta has migrated to petabencana.id where the service will eventually be expanded to Jakarta, Surabaya and Bandung.
What impact does this have on flood realtime and the petajakarta download tools.
@ivanbusthomi - please check if flood realtime is working
@ivanbusthomi - please check if the petajakarta download works

There is nothing on the new website to explain the data or API

See original ticket at https://github.com/inasafe/inasafe/issues/3641 for further discussion.

**Comment by gubuntu** [comment] 2017-02-17 09:26
change text on website (from pj to pb) then close

**Comment by gubuntu** [comment] 2017-02-21 10:21
@Charlotte-Morgan commented in Gitter on 20 Feb:
- kartoza to obtain hourly data
- inaSAFE runs a report every 6 hours for the last 6 hours
- the report should include all rw flooded during the last 6 hours and the deepest water in the last 6 hours

**Comment by lucernae** [comment] 2017-04-11 10:45
Duplicate of #73

**Closed** 2017-04-11 10:45 UTC
Labels: bug, enhancement, feature request, in progress, realtime processor
