### ISSUE TITLE
EQ use ITB Bayesian model

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#30] opened 2017-01-30 10:33 UTC
Switch impact function to use ITB Bayesian Model.
Should be trivial.

See original ticket at https://github.com/inasafe/inasafe/issues/3694 for further discussion.

**Comment by lucernae** [comment] 2017-02-17 09:25
check that this is really working

**Comment by lucernae** [comment] 2017-03-23 23:31
I checked on the code and result, nothing seems to be wrong.
So, I was beginning to suspect the algorithm, just to make sure that it is sane.

In ITB Fatality (inherited in Bayesian), I found this line which seems to calculate the total fatalities:

```
total_fatalities_raw = numpy.nansum(number_of_fatalities.values(), axis=0)
self.total_fatalities = numpy.median(total_fatalities_raw)
```

Now, since it will only take median value, it happens that in ITBBayesian, total_fatalities_raw is 2D array with very sparse values. There are so many zeroes, that the median is almost always 0 (because 0 is always in the middle of the distributions).

This behaviour is different in ITBFatality. In that case, total_fatalities_raw is only a value. Not an array. because number_of_fatalities.values() is just 1D array, which is if get summed, the result is just a value.

Is it ok to assume that total_fatalities_raw is just a value? So it might be the step when doing summation is wrong, perhaps it was supposed to be summing all elements in 2D array of number_of_fatalities? This is because in ITBBayesian, the fatality_rate is taken from csv file, which is a 2D array for each MMI.

CC @timlinux @hadighasemi

**Comment by gubuntu** [comment] 2017-04-13 07:31
@lucernae please chase this up. Who is best placed to answer your questions?

**Comment by Charlotte-Morgan** [comment] 2017-04-13 08:16
@hadighasemi  - please comment on this ticket
cc @RikkiWeber

**Comment by Charlotte-Morgan** [comment] 2017-07-13 06:31
@hadighasemi - we really need your input on this ticket please

**Comment by dynaryu** [comment] 2017-07-17 04:36
@lucernae @gubuntu 
Hi, my name is Hyeuk, who wrote the code. 
Regarding the questions raised by @lucernae, you might want to use mean instead of median if you want to avoid zero estimate. The median was used just to pick one number from a distribution. ITB Bayesian does compute fatality estimate differently from other models; it gives a distribution rather than a single number, but the current INASAFE reporting system does not support the distribution (or probability table), that's why I added median part, which has nothing to do with actual model or bayesian method.  
 I'm happy to answer or clarify any further questions.

**Comment by Charlotte-Morgan** [comment] 2017-07-17 05:57
thanks @dynaryu and @hadighasemi  for the advice.
@lucernae - please note that realtime should be using the same default EQ model as used in desktop. ie it should use the ITB Bayesian Fatality model. If you need to change anything in the model - ie mean and not median, please make sure this is done for all InaSAFE and documented.
cc @timlinux @Gustry

**Comment by lucernae** [comment] 2017-07-24 12:47
Hi @dynaryu, @hadighasemi and @Charlotte-Morgan. On my part, I'm just more concerned with the value type that I need to report (not clear for me). To illustrate this, the current report show this:

<img width="344" alt="screen shot 2017-07-24 at 19 33 37" src="https://user-images.githubusercontent.com/831865/28523557-3ad2ff24-70a7-11e7-9af6-9f7dbf1725c1.png">

The number next to Estimated Fatalities is a range, 0 - 100 is an example of range reported in above pdf screenshot. In previous impact function that we used, ITB Fatality returns a value then on the reporting side, it just shows which range does that value fall into.
In ITB Bayesian, I had trouble understanding what kind of number I need to show to user? Was it a range like this? Or was it a probability distribution? 
Because we are currently using ITB Bayesian but the number that we reported (I think) does not represent the output of this model. In the Bayesian model, the output is a probability distribution for each MMI scale. I don't know how to convey this information into the range format like previously.
So, what is your suggested way for presenting this Fatalities information?

**Comment by Charlotte-Morgan** [comment] 2017-08-03 05:23
For now a range like this, in future a distribution

**Comment by Charlotte-Morgan** [comment] 2017-08-08 06:16
@ivanbusthomi  - can you please liaise with @dynaryu and @hadighasemi  to find out if they are concerned about the issues raised by @lucernae

**Comment by ivanbusthomi** [comment] 2017-08-08 06:19
OK @Charlotte-Morgan

**Comment by gubuntu** [comment] 2017-09-27 07:09
this is fixed in InaSAFE 4 - it will always show the median of the probability distribution. Open a new issue when we want to change the legend to represent the distribution

**Comment by Charlotte-Morgan** [comment] 2017-12-18 06:40
Hi @gubuntu , @lucernae  - I am reopening this.
it appears that this is a problem and may need to be a priority in the migration to v 4

cc
@timlinux @hadighasemi @RikkiWeber @ivanbusthomi @ismailsunni @Gustry

**Comment by lucernae** [comment] 2017-12-18 07:44
CMIIW, but this is fixed in InaSAFE 4, right? So, if we migrate it, it will be fixed. The problem is in v3.5

**Comment by Gustry** [comment] 2017-12-18 07:52
@lucernae Do you have an ETA? (for curiosity)

I will investigate the issue with the data provided this morning by Charlotte and Tim

**Comment by Charlotte-Morgan** [comment] 2017-12-20 03:10
@lucernae  - yes. We note that v 3.5 and v4 will give different results.  However, it is best that Realtime results are not misleading. We need to decide if we focus on migration (when do you expect this to be finished ) vs step out to do a bug fix in 3.5 when we spot a potentially big bug that will damage our users confidence in the product.
@gubuntu - we need your guidance on the best use of our resources vs the risk associated with a known bug
cc @RikkiWeber @hadighasemi

**Comment by lucernae** [comment] 2017-12-20 10:27
@ismailsunni now investigates this. For me, even if we fix the bug here in v3.5, there is a chance that it will have a different result with v4, because of the way we use population data.

**Comment by ismailsunni** [comment] 2017-12-20 12:23
This is what I investigated yesterday @lucernae, so the result is the same.

**Comment by lucernae** [comment] 2020-01-06 09:51
Discussion is concluded.
InaSAFE v4 will not use this algorithm.

**Closed by lucernae** 2020-01-06 09:51 UTC
Labels: earthquake, enhancement, in progress, realtime processor
