### ISSUE TITLE
[Realtime] Location / Placenames for EQ realtime

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#40] opened 2017-01-31 06:27 UTC
This afternoon, I've a quickchat with Ibu Dian from Pusdatinmas BNPB.
This is the conclution for our conversation :

    For location of epicentrum
    She gives the suggestion to use the information accordingly with BMKG.
    Maybe we can extract the information from this link http://data.bmkg.go.id/gempaterkini.xml
   
    For the nearby location
    They (as a user) usually want to know the popular city like the capital of district.
    Placenames with population data
    They don't have any data of this.
    As the discussion with @Charlotte-Morgan. I'll try to use the capital of district in our database, and calculate the population in that town based on the percentage of population in rural and urban based on the data from BPS (population census 2010). Then try to compare it with the actual data or with the data from the other agency (if they have).

See original ticket at https://github.com/inasafe/inasafe/issues/2589 for further discussion.

**Comment by timlinux** [comment] 2017-01-31 07:02
Duplicate of #7

**Closed by timlinux** 2017-01-31 07:02 UTC
