### ISSUE TITLE
Ordering issues in Realtime reports

### ISSUE THREAD

**Issue by christodewit** [inasafe/inasafe-realtime#29] opened 2017-01-30 10:32 UTC
Layer in map view were not ordered correctly.
Need workaround.
See original ticket at https://github.com/inasafe/inasafe/issues/3692 for further discussion.

**Comment by lucernae** [comment] 2017-02-06 17:26
linked with #54

**Comment by lucernae** [comment] 2017-05-09 22:07
I already working on this for quite some times with different solutions, and I can't seem to get it right.
There are always discrepancies, and now I can't seem to think for other reason, other than it was some rendering issues in QGIS. So here's my finding, chronologically.

1. Before this becomes an issue. Things were rendered correctly and I didn't even touch the code about layer ordering. Then issues started to pop up when InaSAFE 3 trying to support QGIS 2.14 as LTR. At that time, Realtime Report renderer used QGIS 2.8 (IIRC) and because of this we are having some issues with the QGIS Composer, such as Font style in composer not rendered correctly (Ubuntu font displayed as Times New Roman, font size is different, weird spacing margin, etc). Then we decided to use QGIS 2.14 docker images, and font issues were resolved.

2. Then the layer order began to mixed up sometimes. At that time, QGIS Composer just render the map canvas using layer order specified implicitly in QGIS Legend Interface. I decided that perhaps this is buggy, so I found a workaround by specifying the order explicitly in the QGIS Composer's map canvas. The order itself were taken from QGISMapLayerRegistry. It appears to be solved.

3. Then sometimes the issue still persists. So I concluded that perhaps the order is correct now, but because we re-set the order, it might not have been redrawn correctly. Based on this, I put some code that map canvas should update its cached image. It appears to be solved.

4. Then sometimes the issue still persists. I debug it again, now tracing the layer order more closely. It turns out I made an assumption mistake. QGISMapLayerRegistry stores layers collection in a dictionary, so the order information got lost. I switched again to QGIS Legend Interface to retrieve the layer id order and then set it to map canvas. It appears to be solved.

5. Then I realized that sometimes this is not caused by layer order mixup. Layer order is correct now but some layers didn't render. I didn't have any suspicion on this because I usually test it against small grid.xml in small rural area. Administrative boundary is missing not because it was behind a land, but because it didn't rendered in time before PDF is generated. I got this by replicating issues where there are many administrative boundary. Take a look at this example:

We can see that we mostly see the boundaries, but for some reason in some part, boundary is missing (indicated by red arrow pointer).
<img width="484" alt="screen shot 2017-05-10 at 04 47 19" src="https://cloud.githubusercontent.com/assets/831865/25874362/65d43018-353c-11e7-9ab9-6ec775e576a8.png">

Then, in some cases with the same area extent, and grid.xml (although changed the order). The boundaries can be rendered just fine. Although, strange things are, we can conclude that the contour is on top of island, because the MMI label can be seen in island. However some contours get cropped in Sumatra (either it is below the island, or it didn't get rendered).
<img width="475" alt="screen shot 2017-05-10 at 04 47 35" src="https://cloud.githubusercontent.com/assets/831865/25874622/853772e8-353d-11e7-9bf9-79d0252a4a16.png">

So, I just wanted to confirm with @gubuntu and @timlinux. Perhaps the rendering used some sort async/multi-threaded to draw the layers, to explain why some border is missing? Do we have some sort of thread synchronization method in composer where we can know that the whole thing were finished rendering before we execute export to PDF?

**Comment by gubuntu** [comment] 2017-05-10 10:55
Good PI work @lucernae. 

Try 2.18?

Otherwise if you can replicate and get to the bottom of it then log an issue upstream with QGIS (which we can then maybe fix)

**Comment by lucernae** [comment] 2017-05-15 04:29
Will try new QGIS LTR 2.14 first.

**Comment by lucernae** [comment] 2017-05-15 23:40
Using QGIS LTR 2.14 still doesn't work. Same problem.
I'm thinking on creating smaller unittest to demonstrate the problem to log issue upstream.

**Comment by lucernae** [comment] 2017-05-19 06:45
Closing this.

**Closed** 2017-05-19 06:45 UTC
Labels: bug, realtime processor
